from tkinter import *
import random
import sys

frameelements = [
    {"frame": "Quantity",
     "itens": {
         "amount": "n",
         "degree": "n",
         "extent": "n",
         "level": "n",
         "number": "n",
         "quantity": "n"}
     },

    {"frame": "Aggregate",
     "itens": {
         "army": "n",
         "assemblage": "n",
         "assembly": "n",
         "assortment": "n",
         "band": "n",
         "batch": "n",
         "bevy": "n",
         "body": "n",
         "book": "n",
         "brood": "n",
         "bunch": "n",
         "circle": "n",
         "claque": "n",
         "class": "n",
         "clique": "n",
         "clump": "n",
         "cluster": "n",
         "clutch": "n",
         "cohort": "n",
         "collection": "n",
         "colony": "n",
         "combination": "n",
         "community": "n",
         "corps": "n",
         "coterie": "n",
         "covey": "n",
         "crew": "n",
         "crop": "n",
         "crowd": "n",
         "family": "n",
         "flock": "n",
         "flotilla": "n",
         "force": "n",
         "gaggle": "n",
         "gang": "n",
         "group": "n",
         "harem": "n",
         "heap": "n",
         "herd": "n",
         "horde": "n",
         "host": "n",
         "huddle": "n",
         "legion": "n",
         "mob": "n",
         "multiplicity": "n",
         "multitude": "n",
         "pack": "n",
         "package": "n",
         "party": "n",
         "passel": "n",
         "population": "n",
         "posse": "n",
         "quartet": "n",
         "quintet": "n",
         "repertoire": "n",
         "repertory": "n",
         "school": "n",
         "set": "n",
         "sextet": "n",
         "shoal": "n",
         "slew": "n",
         "squad": "n",
         "stand": "n",
         "swarm": "n",
         "team": "n",
         "throng": "n",
         "tribe": "n",
         "trio": "n",
         "variety": "n"}
     },

    {"frame": "Medical_condition",
     "itens": {
         "acromegaly": "n",
         "affliction": "n",
         "AIDS": "n",
         "ailment": "n",
         "Alzheimer's": "n",
         "amnesia": "n",
         "anorexia": "n",
         "arthritis": "n",
         "asphyxia": "n",
         "asthma": "n",
         "bacterial meningitis": "n",
         "bronchitis": "n",
         "cancer": "n",
         "candida": "n",
         "cataract": "n",
         "cholangitis": "n",
         "cholecystitis": "n",
         "cholera": "n",
         "cirrhosis": "n",
         "cold": "n",
         "colitis": "n",
         "condition": "n",
         "conjunctivitis": "n",
         "cryptosporidiosis": "n",
         "depression": "n",
         "dermatitis": "n",
         "develop": "v",
         "diabetes": "n",
         "diarrhea": "n",
         "diphtheria": "n",
         "disease": "n",
         "disorder": "n",
         "diverticulosis": "n",
         "dysmenorrhoea": "n",
         "eczema": "n",
         "flu": "n",
         "German measles": "n",
         "health": "n",
         "healthy": "a",
         "hepatitis": "n",
         "hernia": "n",
         "hypertension": "n",
         "hypoglycaemia": "n",
         "ill": "a",
         "illness": "n",
         "infection": "n",
         "influenza": "n",
         "jaundice": "n",
         "leprosy": "n",
         "leukemia": "n",
         "malaria": "n",
         "malnourishment": "n",
         "malnutrition": "n",
         "measles": "n",
         "meningitis": "n",
         "menorrhagia": "n",
         "mumps": "n",
         "paraplegic": "a",
         "plague": "n",
         "polio": "n",
         "psoriasis": "n",
         "pyelonephritis": "n",
         "rosacea": "n",
         "rubella": "n",
         "schizophrenia": "n",
         "sciatica": "n",
         "shock": "n",
         "sick": "a",
         "sickness": "n",
         "stenosis": "n",
         "stress": "n",
         "strongylosis": "n",
         "syndrome": "n",
         "syphilis": "n",
         "tetanus": "n",
         "tuberculosis": "n",
         "tumor": "n",
         "ulcer": "n",
         "unwell": "a",
         "wound": "n"}
     },

    {"frame": "Cardinal_number",
     "itens": {
         "billion": "num",
         "brace": "n",
         "couple": "n",
         "dual": "a",
         "eight": "num",
         "fifteen": "num",
         "fifty-two": "num",
         "fifty": "num",
         "five hundred": "num",
         "five": "num",
         "forty": "num",
         "four": "num",
         "fourteen": "n",
         "hundred": "num",
         "million": "num",
         "nine": "num",
         "ninety": "num",
         "number": "n",
         "one": "num",
         "pair": "n",
         "score": "n",
         "seven": "num",
         "seventy-four": "num",
         "seventy": "num",
         "six": "num",
         "sixty": "num",
         "ten": "num",
         "thirty": "num",
         "thousand": "num",
         "three": "num",
         "twelve": "num",
         "twenty-five": "num",
         "twenty-one": "num",
         "twenty-seven": "num",
         "twenty": "num",
         "two hundred": "num",
         "two": "num",
         "zero": "num"}
     },

    {"frame": "Change_position_on_a_scale",
     "itens": {
         "accelerated": "a",
         "advance": "v",
         "balloon": "v",
         "climb": "v",
         "contract": "v",
         "contraction": "n",
         "decline": "n",
         "decline": "v",
         "decrease": "n",
         "decrease": "v",
         "depressed": "a",
         "depression": "n",
         "diminish": "v",
         "dip": "v",
         "double": "v",
         "down": "prep",
         "drop": "v",
         "dwindle": "v",
         "edge": "v",
         "elevated": "a",
         "elevation": "n",
         "escalation": "n",
         "explode": "v",
         "explosion": "n",
         "fall": "n",
         "fall": "v",
         "fluctuate": "v",
         "fluctuation": "n",
         "gain": "n",
         "gain": "v",
         "grow": "v",
         "growing": "a",
         "growth": "n",
         "hike": "n",
         "increase": "n",
         "increase": "v",
         "increasingly": "adv",
         "jump": "v",
         "lower": "v",
         "move": "v",
         "mushroom": "v",
         "plummet": "v",
         "reach": "v",
         "rise": "n",
         "rise": "v",
         "rocket": "v",
         "shift": "n",
         "shift": "v",
         "skyrocket": "v",
         "slide": "v",
         "soar": "v",
         "swell": "v",
         "swing": "v",
         "triple": "v",
         "tumble": "n",
         "tumble": "v"}
     },

    {"frame": "Gizmo",
     "itens": {
         "apparatus": "n",
         "appliance": "n",
         "centrifuge": "n",
         "contraption": "n",
         "core": "n",
         "device": "n",
         "equipment": "n",
         "gadget": "n",
         "gear": "n",
         "implement": "n",
         "instrument": "n",
         "level": "n",
         "machine": "n",
         "mechanical": "a",
         "player": "n",
         "range": "n",
         "system": "n",
         "technology": "n",
         "tool": "n",
         "utensil": "n"}
     },

    {"frame": "Mean",
     "itens": {
         "approach": "n",
         "by": "prep",
         "course of action": "n",
         "how": "adv",
         "means": "n",
         "mechanism": "n",
         "method": "n",
         "modus operandi": "n",
         "nuts and bolts": "n",
         "on": "prep",
         "procedure": "n",
         "process": "n",
         "recipe [cooking]": "n",
         "tactic": "n",
         "technique": "n",
         "way": "n"}
     },

    {"frame": "Political_locale",
     "itens": {
         "barony": "n",
         "borough": "n",
         "city-state": "n",
         "city": "n",
         "commonwealth": "n",
         "country": "n",
         "county": "n",
         "diocese": "n",
         "district": "n",
         "duch": "n",
         "empire": "n",
         "federal": "a",
         "fiefdom": "n",
         "global": "a",
         "international": "a",
         "internationally": "adv"}
     },

    {"frame": "Using",
     "itens": {
         "application": "n",
         "apply": "v",
         "avail oneself": "v",
         "employ": "v",
         "employment": "n",
         "exercise": "v",
         "operate": "v",
         "operation": "n",
         "operational": "a",
         "use": "n",
         "use": "v",
         "utilisation": "n",
         "utilise": "v"}
     },

    {"frame": "temporal_collocation",
     "itens": {
         "ancient": "a",
         "around": "prep",
         "as of": "prep",
         "as": "adv",
         "at present": "adv",
         "at the time": "adv",
         "at": "prep",
         "back then": "n",
         "current": "a",
         "currently": "adv",
         "during": "prep",
         "early.": "a",
         "future": "a",
         "in": "prep",
         "lately": "adv",
         "modern": "a",
         "newly": "adv",
         "no longer": "adv",
         "now": "adv",
         "nowadays": "n",
         "of late": "adv",
         "on": "prep",
         "over": "prep",
         "overnight": "adv",
         "prehistoric": "a",
         "recently": "adv",
         "then": "adv",
         "today": "n",
         "ultimately": "adv",
         "when": "adv",
         "while": "c",
         "within": "prep"}
     },

    {"frame": "statement",
     "itens": {
         "acknowledge": "v",
         "acknowledgment": "n",
         "add": "v",
         "address": "v",
         "admission": "n",
         "allegation": "n",
         "allege": "v",
         "allow": "v",
         "announce": "v",
         "announcement": "n",
         "assert": "v",
         "assertion": "n",
         "attest": "v",
         "aver": "v",
         "avow": "v",
         "avowal": "n",
         "be like": "v",
         "caution": "n",
         "caution": "v",
         "challenge": "v",
         "claim": "n",
         "claim": "v",
         "comment": "n",
         "comment": "v",
         "concession": "n",
         "confirm": "v",
         "conjecture": "n",
         "conjecture": "v",
         "contend": "v",
         "contention": "n",
         "declaration": "n",
         "declare": "v",
         "denial": "n",
         "describe": "v",
         "detail": "v",
         "exclaim": "v",
         "exclamation": "n",
         "explain": "v",
         "explanation": "n",
         "gloat": "v",
         "hazard": "v",
         "insist": "v",
         "insistence": "n",
         "maintain": "v",
         "mention": "n",
         "mention": "v",
         "message": "n",
         "note": "v",
         "observe": "v",
         "pout": "v",
         "preach": "v",
         "proclaim": "v",
         "proclamation": "n",
         "profess": "v",
         "promulgation": "n",
         "pronounce": "v",
         "pronouncement": "n",
         "proposal": "n",
         "propose": "v",
         "proposition": "n",
         "reaffirm": "v",
         "recount": "v",
         "refute": "v",
         "reiterate": "v",
         "relate": "v",
         "remark": "n",
         "remark": "v",
         "report": "n",
         "report": "v",
         "say": "v",
         "smirk": "v",
         "speak": "v",
         "state": "v",
         "statement": "n",
         "suggest": "v",
         "talk": "v",
         "tell": "v",
         "venture": "v",
         "write": "v"}
     },

    {"frame": "Purpose",
     "itens": {
         "aim": "n",
         "aim": "v",
         "application": "n",
         "bent": "a",
         "determined": "a",
         "goal": "n",
         "in order": "adv",
         "intend": "v",
         "intent": "a",
         "intention": "n",
         "mean": "v",
         "object": "n",
         "objective": "n",
         "plan": "n",
         "plan": "v",
         "purpose": "n",
         "target": "n",
         "use": "n"}
     },

    {"frame": "Text",
     "itens": {
         "account": "n",
         "article": "n",
         "autobiography": "n",
         "ballad": "n",
         "benediction": "n",
         "biography": "n",
         "book": "n",
         "booklet": "n",
         "brochure": "n",
         "bulletin": "n",
         "chronicle": "n",
         "comedy": "n",
         "diary": "n",
         "drama": "n",
         "edition": "n",
         "editorial": "n",
         "elegy": "n",
         "epic": "a",
         "epic": "n",
         "epigram": "n",
         "epilogue": "n",
         "epistle": "n",
         "essay": "n",
         "eulogy": "n",
         "exemplum": "n",
         "fable": "n",
         "fanzine": "n",
         "festschrift": "n",
         "fiction": "n",
         "grimoire": "n",
         "hagiography": "n",
         "haiku": "n",
         "handbook": "n",
         "hardback": "n",
         "history": "n",
         "imprecation": "n",
         "issue": "n",
         "journal": "n",
         "lay": "n",
         "letter": "n",
         "life": "n",
         "limerick": "n",
         "list": "n",
         "literature": "n",
         "lyric": "n",
         "mag": "n",
         "magazine": "n",
         "manual": "n",
         "manuscript": "n",
         "material": "n",
         "meditation": "n",
         "memoir": "n",
         "missive": "n",
         "monograph": "n",
         "mystery": "n",
         "newspaper": "n",
         "novel": "n",
         "novelette": "n",
         "novella": "n",
         "obituar": "n",
         "ode": "n",
         "pamphlet": "n",
         "paper [article]": "n",
         "paper [newspaper]": "n",
         "paperback": "n",
         "periodical": "n",
         "poem": "n",
         "poetry": "n",
         "publication": "n",
         "record": "n",
         "report": "n",
         "rhyme": "n",
         "saga": "n",
         "screenplay": "n",
         "script": "n",
         "sermon": "n",
         "song": "n",
         "sonnet": "n",
         "speech": "n",
         "spellbook": "n",
         "tetralogy": "n",
         "textbook": "n",
         "thriller": "n",
         "tome": "n",
         "tract": "n",
         "tractate": "n",
         "tragedy": "n",
         "treatise": "n",
         "trilogy": "n",
         "volume": "n",
         "whodunit": "n",
         "writings": "n"}
     },

    {"frame": "network",
     "itens": {
         "network": "n",
         "web": "n"}
     },

    {"frame": "Causation",
     "itens": {
         "because of": "prep",
         "because": "c",
         "bring about": "v",
         "bring on": "v",
         "bring": "v",
         "causative": "a",
         "cause": "n",
         "cause": "v",
         "consequence": "n",
         "consequent": "a",
         "consequential": "a",
         "dictate": "v",
         "due to": "prep",
         "for": "c",
         "force": "v",
         "give rise": "v",
         "induce": "v",
         "lead (to)": "v",
         "leave": "v",
         "legacy": "n",
         "make": "v",
         "mean": "v",
         "motivate": "v",
         "precipitate": "v",
         "put": "v",
         "raise": "v",
         "reason": "n",
         "render": "v",
         "responsible": "a",
         "result (in)": "v",
         "result": "n",
         "resultant": "a",
         "resulting": "a",
         "see": "v",
         "send": "v",
         "since": "c",
         "so": "c",
         "sway": "v",
         "wreak": "v"}
     },

    {"frame": "Dimension",
     "itens": {
         "across": "adv",
         "area": "n",
         "around": "adv",
         "breadth": "n",
         "broad": "a",
         "circumference": "n",
         "deep": "a",
         "depth": "n",
         "grand": "a",
         "heigh": "n",
         "high": "a",
         "length": "n",
         "level": "n",
         "long": "a",
         "measure": "v",
         "tall": "a",
         "thick": "a",
         "weigh": "v",
         "weight": "n",
         "wide": "a",
         "width": "n",
         "work": "n"}
     },

    {"frame": "Substance",
     "itens": {
         "aluminum": "n",
         "atropine": "n",
         "calcium": "n",
         "cement": "n",
         "chemical": "n",
         "fertilizer": "n",
         "frankincense": "n",
         "gas": "n",
         "glass": "n",
         "iron": "n",
         "juice": "n",
         "liquid": "n",
         "material": "n",
         "metal": "n",
         "methane": "n",
         "mud": "n",
         "myrrh": "n",
         "oil": "n",
         "ore": "n",
         "oxygen": "n",
         "paper": "n",
         "petroleum": "n",
         "plutonium": "n",
         "sand": "n",
         "solid": "n",
         "uranium": "n",
         "water": "n",
         "yellowcake": "n"}
     },

    {"frame": "education_teaching",
     "itens": {
         "academic": "a",
         "coach": "v",
         "cram": "v",
         "educate": "v",
         "education": "n",
         "educational": "a",
         "graduate": "n",
         "instruct": "v",
         "instruction": "n",
         "learn": "v",
         "lecturer": "n",
         "master": "v",
         "professor": "n",
         "protege": "n",
         "pupil": "n",
         "school": "v",
         "schoolmaster": "n",
         "schoolmistress": "n",
         "schoolteacher": "n",
         "student": "n",
         "study": "v",
         "teach": "v",
         "teacher": "n",
         "train": "v",
         "training": "n",
         "tutee": "n",
         "tutor": "n",
         "tutor": "v"}
     },

    {"frame": "research",
     "itens": {
         "investigate": "v",
         "research": "n",
         "research": "v"}
     },

    {"frame": "increment",
     "itens": {
         "additional": "a",
         "another": "a",
         "another": "n",
         "further": "a",
         "more": "a",
         "more": "n",
         "other": "a",
         "other": "n"}
     },

    {"frame": "intentionally_act",
     "itens": {
         "act": "n",
         "act": "v",
         "action": "n",
         "activity": "n",
         "actor": "n",
         "agent": "n",
         "carry out": "v",
         "conduct": "v",
         "deed": "n",
         "do": "v",
         "doing": "n",
         "engage": "v",
         "execute": "v",
         "measure": "n",
         "move": "n",
         "perform": "v",
         "step": "n"}
     },

    {"frame": "objective_influence",
     "itens": {
         "affect": "v",
         "effect": "n",
         "impact": "n",
         "impact": "v",
         "influence": "n",
         "influence": "v",
         "power": "n"}
     },

    {"frame": "similarity",
     "itens": {
         "alike": "a",
         "deviant": "a",
         "deviate": "v",
         "deviation": "n",
         "differ": "v",
         "difference [count]": "n",
         "difference": "n",
         "different": "a",
         "discrepancy": "n",
         "discrepant": "a",
         "disparate": "a",
         "disparity": "n",
         "dissimilar": "a",
         "dissimilarity [mass]": "n",
         "dissimilarity": "n",
         "distinct": "a",
         "distinction": "n",
         "image": "n",
         "like": "a",
         "like": "n",
         "like": "n",
         "like": "a",
         "mimic": "n",
         "parallel": "prep",
         "resemblance": "v",
         "resemble": "n",
         "ringer": "n",
         "similar": "v",
         "similarity [count]": "n",
         "similarity [mass]": "a",
         "spitting image": "n",
         "take (after)": "n",
         "unlike": "n",
         "unlike": "v",
         "variant": "prep",
         "vary": "n",
         "very image": "v"}
     },

    {"frame": "being_obligated",
     "itens": {
         "assignment": "n",
         "bound": "a",
         "commission": "n",
         "contract": "n",
         "duty": "n",
         "imposition": "n",
         "job": "n",
         "mission": "n",
         "obligated": "a",
         "obligation": "n",
         "obliged": "a",
         "responsibility": "n",
         "task": "n"}
     },

    {"frame": "evidence",
     "itens": {
         "argue": "v",
         "argument": "n",
         "assure": "v",
         "attest": "v",
         "confirm": "v",
         "contradict": "v",
         "corroborate": "v",
         "credence [lend]": "n",
         "demonstrate": "v",
         "demonstration": "n",
         "disprove": "v",
         "evidence": "n",
         "evidence": "v",
         "evince": "v",
         "from": "prep",
         "illustrate": "v",
         "imply": "v",
         "indicate": "v",
         "mean": "v",
         "point (to)": "v",
         "proof": "n",
         "prove": "v",
         "reflect": "v",
         "reveal": "v",
         "rule out": "v",
         "show": "v",
         "substantiate": "v",
         "suggest": "v",
         "support": "v",
         "tell": "v",
         "testify": "v",
         "verify": "v"}
     },

    {"frame": "building",
     "itens": {
         "assemble": "v",
         "assembly": "n",
         "build": "v",
         "construct": "v",
         "construction [entity]": "n",
         "construction": "n",
         "erect": "v",
         "fashion": "v",
         "fit together": "v",
         "glue": "v",
         "make": "v",
         "piece together": "v",
         "put together": "v",
         "raise": "v",
         "weld": "v"}
     },

    {"frame": "capability",
     "itens": {
         "ability": "n",
         "able": "a",
         "can": "v",
         "capability": "n",
         "capable": "a",
         "capacity": "n",
         "inability": "n",
         "incapable": "a",
         "incapacity": "n",
         "potential": "a",
         "potential": "n",
         "power [statistical]": "n",
         "power": "n",
         "powerful": "a",
         "powerless": "a",
         "powerlessness": "n",
         "unable": "a"}
     },

    {"frame": "cognitive_connection",
     "itens": {
         "associated": "a",
         "connected": "a",
         "have to do (with)": "v",
         "identify with": "v",
         "linked": "a",
         "related": "a",
         "relationship": "n",
         "tied": "a"}
     },

    {"frame": "importance",
     "itens": {
         "acute": "a",
         "considerable": "a",
         "count": "v",
         "critical": "a",
         "crucial": "a",
         "decisive": "a",
         "epic": "a",
         "fundamental": "a",
         "import": "n",
         "importance": "n",
         "important": "a",
         "instrumental": "a",
         "key": "a",
         "landmark": "n",
         "main": "a",
         "major": "a",
         "pivotal": "a",
         "priority": "n",
         "serious": "a",
         "seriously": "adv",
         "significance": "n",
         "significant": "a",
         "vital": "a"}
     },

    {"frame": "awareness",
     "itens": {
         "aware": "a",
         "awareness": "n",
         "believe": "v",
         "cognizant": "a",
         "comprehend": "v",
         "comprehension": "n",
         "conceive": "v",
         "conception": "n",
         "conscious": "a",
         "consciousness": "n",
         "hunch": "n",
         "idea": "n",
         "ignorance": "n",
         "imagine": "v",
         "know": "v",
         "knowledge": "n",
         "knowledgeable": "a",
         "presume": "v",
         "presumption": "n",
         "reckon": "v",
         "supposition": "n",
         "suspect": "v",
         "suspicion": "n",
         "think": "v",
         "though": "n",
         "understand": "v",
         "understanding": "n",
         "unknown": "a"}
     },

    {"frame": "reasoning",
     "itens": {
         "argue": "v",
         "argument": "n",
         "case": "n",
         "demonstrate": "v",
         "demonstration": "n",
         "disprove": "v",
         "polemic": "n",
         "prove": "v",
         "reason": "v",
         "reasoning": "n",
         "show": "v"}
     },

    {"frame": "expertise",
     "itens": {
         "ace": "a",
         "ace": "n",
         "adept": "a",
         "adept": "n",
         "adeptness": "n",
         "amateur": "a",
         "amateur": "n",
         "awful": "a",
         "bad": "a",
         "buff": "n",
         "competence": "n",
         "competent": "a",
         "connoisseur": "n",
         "conversance": "n",
         "conversant": "a",
         "crack": "a",
         "dreadful": "a",
         "excel": "v",
         "excellent": "a",
         "experience": "n",
         "experienced": "a",
         "expert": "a",
         "expert": "n",
         "expertise": "n",
         "familiar": "a",
         "fantastic": "a",
         "good": "a",
         "great": "a",
         "guru": "n",
         "incompetence": "n",
         "incompetent": "a",
         "incredible": "a",
         "inept": "a",
         "ineptitude": "n",
         "ineptness": "n",
         "inexperienced": "a",
         "inexpert": "a",
         "know-how": "n",
         "knowledgeable": "a",
         "lay": "a",
         "layman": "n",
         "master": "a",
         "master": "n",
         "mastery": "n",
         "maven": "n",
         "mediocre": "a",
         "new (to)": "a",
         "novice": "n",
         "outstanding": "a",
         "pro": "n",
         "proficiency": "n",
         "proficient": "a",
         "prowess": "n",
         "skilful": "a",
         "skill": "n",
         "skilled": "a",
         "so-so": "a",
         "specialist": "n",
         "splendid": "a",
         "strong": "a",
         "stupendous": "a",
         "superb": "a",
         "superlative": "a",
         "terrible": "a",
         "terrific": "a",
         "tremendous": "a",
         "versed": "a",
         "virtuosity": "n",
         "virtuoso": "n",
         "well-versed": "a",
         "whiz": "n",
         "wizard": "n",
         "wonderful": "a"}
     },

    {"frame": "event",
     "itens": {
         "development": "n",
         "episode": "n",
         "event": "n",
         "go on": "v",
         "happen": "v",
         "incident": "n",
         "occur": "v",
         "take place": "v",
         "transpire": "v"}
     },

    {"frame": "categorization",
     "itens": {
         "bracket": "v",
         "categorization": "n",
         "categorize": "v",
         "category": "n",
         "class": "v",
         "classification": "n",
         "classify": "v",
         "conceive": "v",
         "consider": "v",
         "construe": "v",
         "count": "v",
         "deem": "v",
         "define": "v",
         "identify": "v",
         "interpret": "v",
         "interpretation": "n",
         "peg": "v",
         "perceive": "v",
         "pigeonhole": "v",
         "read": "v",
         "regard": "v",
         "render": "v",
         "see": "v",
         "stereotype": "v",
         "translate": "v",
         "typecast": "v",
         "understand": "v",
         "view": "v"}
     },

    {"frame": "likelihood",
     "itens": {
         "assured": "a",
         "bound": "a",
         "can": "v",
         "certain": "a",
         "certainly": "adv",
         "certainty": "n",
         "chance": "n",
         "guaranteed": "a",
         "impossible": "a",
         "improbability": "n",
         "liable": "a",
         "likelihood": "n",
         "likely": "a",
         "likely": "adv",
         "long": "a",
         "may": "v",
         "might": "v",
         "must": "v",
         "possibility": "n",
         "possible": "a",
         "possibly": "adv",
         "probability": "n",
         "probable": "a",
         "probably": "adv",
         "prone": "a",
         "sure": "a",
         "surely": "adv",
         "tend": "v",
         "undoubtedl": "adv",
         "unlikely": "a",
         "would": "v"}
     },

    {"frame": "frequency",
     "itens": {
         "all the time": "adv",
         "always": "adv",
         "annua": "a",
         "at times": "adv",
         "bi-annual": "a",
         "bi-monthly": "a",
         "biennial": "a",
         "common": "a",
         "constantly": "adv",
         "daily": "a",
         "daily": "adv",
         "every once in a while": "adv",
         "every so often": "adv",
         "every": "prep",
         "fortnightly": "a",
         "frequency": "n",
         "frequen": "a",
         "frequently": "adv",
         "generally": "adv",
         "in general": "adv",
         "infrequent": "a",
         "infrequently": "adv",
         "intermittent": "a",
         "interval": "n",
         "monthly": "a",
         "never": "adv",
         "nightly": "a",
         "normally": "adv",
         "now and then": "adv",
         "occasional": "a",
         "occasionally": "adv",
         "off and on": "adv",
         "often": "adv",
         "on and off": "adv",
         "once in a while": "adv",
         "ordinarily": "adv",
         "period": "n",
         "periodic": "a",
         "rare": "a",
         "recurrence": "n",
         "recurrent": "a",
         "recurring": "adv",
         "regularly": "adv",
         "seldom": "a",
         "sometime": "adv",
         "sometimes": "a",
         "sporadic": "adv",
         "time to time": "adv",
         "usually": "a",
         "weekly": "a"}
     },

    {"frame": "calendric_unit",
     "itens": {
         "afternoon": "n",
         "age": "n",
         "April": "n",
         "August": "n",
         "autumn": "n",
         "calendar year": "n",
         "century": "n",
         "dawn": "n",
         "day": "n",
         "daybreak": "n",
         "decade": "n",
         "December": "n",
         "dusk": "n",
         "era": "n",
         "eve": "n",
         "evening": "n",
         "February": "n",
         "fortnight": "n",
         "Friday": "n",
         "holiday": "n",
         "hour": "n",
         "January": "n",
         "July": "n",
         "June": "n",
         "leap year": "n",
         "March": "n",
         "May": "n",
         "midday": "n",
         "midnight": "n",
         "millennium": "n",
         "minute": "n",
         "Monday": "n",
         "month": "n",
         "morn": "n",
         "morning": "n",
         "night": "n",
         "noon": "n",
         "November": "n",
         "October": "n",
         "one day": "n",
         "quarter": "n",
         "rush hour": "n",
         "Saturday": "n",
         "school year": "n",
         "second": "n",
         "September": "n",
         "spring": "n",
         "summer": "n",
         "Sunday": "n",
         "Thursday": "n",
         "today": "n",
         "tomorrow": "n",
         "tonight": "n",
         "Tuesday": "n",
         "twiligh": "n",
         "Wednesday": "n",
         "week": "n",
         "weekday": "n",
         "weekend": "n",
         "weeknight": "n",
         "winter": "n",
         "year": "n",
         "yesterday": "n"}
     },

    {"frame": "assessing",
     "itens": {
         "appraisal": "n",
         "appraise": "v",
         "assess": "v",
         "assessment": "n",
         "evaluate": "v",
         "evaluation": "n",
         "grade": "v",
         "judge": "v",
         "rank": "v",
         "rate": "v",
         "reappraisal": "n",
         "reappraise": "v",
         "review": "v",
         "value": "v",
         "weigh": "v"}
     },

    {"frame": "cause_to_make_progress",
     "itens": {
         "advance": "v",
         "develop": "v",
         "gains": "n",
         "improve": "v",
         "improved": "a",
         "mature": "v",
         "modernization": "n",
         "perfect": "v"}
     },

    {"frame": "locale_by_use",
     "itens": {
         "airfield": "n",
         "base": "n",
         "bathhouse": "n",
         "boutique": "n",
         "campus": "n",
         "canal": "n",
         "cemetery": "n",
         "center": "n",
         "city": "n",
         "college": "n",
         "complex": "n",
         "compound": "n",
         "country": "n",
         "countryside": "n",
         "court": "n",
         "courtyard": "n",
         "depot": "n",
         "development": "n",
         "downtown": "n",
         "facility": "n",
         "factory": "n",
         "farm": "n",
         "field": "n",
         "firehouse": "n",
         "gallery": "n",
         "garden": "n",
         "green": "n",
         "harbor": "n",
         "headquarters": "n",
         "hedge": "n",
         "installation": "n",
         "institute": "n",
         "lab": "n",
         "laboratory": "n",
         "mine": "n",
         "museum": "n",
         "open space": "a",
         "park": "n",
         "park[]": "n",
         "parking lot": "n",
         "plant": "n",
         "plantation": "n",
         "port": "n",
         "post office": "n",
         "pub": "n",
         "ranch": "n",
         "range": "n",
         "reactor": "n",
         "restaurant": "n",
         "rural": "a",
         "safe house": "n",
         "school": "n",
         "settlement": "n",
         "shop.": "n",
         "silo": "n",
         "site": "n",
         "square": "n",
         "station": "n",
         "theater": "n",
         "university": "n",
         "urban": "a",
         "village": "n",
         "work": "n",
         "zoo": "n"}
     },

    {"frame": "vehicle",
     "itens": {
         "aircraft": "n",
         "airplane": "n",
         "ambulance": "n",
         "automobile": "n",
         "bicycle": "n",
         "bike": "n",
         "bird": "n",
         "boat": "n",
         "buggy": "n",
         "bus": "n",
         "cab": "n",
         "canoe": "n",
         "car": "n",
         "carriage": "n",
         "cart": "n",
         "chopper": "n",
         "coach": "n",
         "convertible": "n",
         "ferry": "n",
         "helicopte": "n",
         "helo": "n",
         "kayak": "n",
         "limousine": "n",
         "liner": "n",
         "lorry": "n",
         "minivan": "n",
         "pick-up": "n",
         "plane": "n",
         "schooner": "n",
         "scooter": "n",
         "sedan": "n",
         "ship": "n",
         "submarine": "n",
         "tank car": "n",
         "tank": "n",
         "taxi": "n",
         "toboggan": "n",
         "train": "n",
         "tram": "n",
         "tricycle": "n",
         "truck": "n",
         "van": "n",
         "vehicle": "n",
         "vessel": "n",
         "warplane": "n",
         "yacht": "n"}
     },

    {"frame": "electricity",
     "itens": {
         "current": "n",
         "electric power": "n",
         "electric": "a",
         "electrical power": "n",
         "electrical": "a",
         "electricity": "n",
         "energy": "n",
         "hydroelectric": "a",
         "hydroelectricity": "n",
         "juice": "n",
         "photoelectric": "a",
         "photoelectricity": "n",
         "power": "n"}
     },

    {"frame": "leadership",
     "itens": {
         "administer": "v",
         "administration": "n",
         "authority": "n",
         "baron": "n",
         "bishop": "n",
         "boss": "n",
         "caliph": "n",
         "captain": "n",
         "CEO": "n",
         "chair": "v",
         "chairman": "n",
         "chairperson": "n",
         "charge": "n",
         "chief executive officer": "n",
         "chief": "n",
         "chieftain": "n",
         "command": "n",
         "command": "v",
         "commandant": "n",
         "commander": "n",
         "commissioner": "n",
         "congressman": "n",
         "congresswoman": "n",
         "crown prince": "n",
         "despot": "n",
         "dictator": "n",
         "diplomat": "n",
         "director general": "n",
         "director": "n",
         "doyen": "n",
         "doyenne": "n",
         "drug lord": "n",
         "duchess": "n",
         "emperor": "n",
         "empress": "n",
         "executive": "n",
         "general": "n",
         "govern": "v",
         "government": "n",
         "governor": "n",
         "head": "n",
         "head": "v",
         "headmaster": "n",
         "high-priest": "n",
         "hold sway": "v",
         "imam": "n",
         "kaiser": "n",
         "khan": "n",
         "khedive": "n",
         "king": "n",
         "lawmaker": "n",
         "lead": "v",
         "leader": "n",
         "leadership": "n",
         "legislator": "n",
         "legislature": "n",
         "maharaja": "n",
         "major general": "a",
         "mayor": "n",
         "minister": "n",
         "mogul": "n",
         "monarch": "n",
         "officer": "n",
         "official": "n",
         "overlord": "n",
         "pasha": "n",
         "power [govt]": "n",
         "power [rule]": "n",
         "premier": "n",
         "preside": "v",
         "president [non-political]": "n",
         "president [political]": "n",
         "presidential": "a",
         "prime minister": "n",
         "prince": "n",
         "principal": "n",
         "queen": "n",
         "rector": "n",
         "regime": "n",
         "reign": "v",
         "representative": "n",
         "rule": "n",
         "rule": "v",
         "ruler": "n",
         "run": "v",
         "satrap": "n",
         "secretary": "n",
         "senate": "n",
         "shah": "n",
         "sheik.": "n",
         "sovereign": "n",
         "spearhead": "v",
         "state": "n",
         "sultan": "n",
         "superintendent": "n",
         "supervisor.": "n",
         "suzerain": "n",
         "tsar": "n",
         "tsarina": "n",
         "tyrant.": "n",
         "vice-captain": "n",
         "vice-chairman": "n",
         "vice-president [non-political]": "n",
         "vice-president [political": "n",
         "vice-principal": "n",
         "viceroy": "n",
         "vizier": "n"}
     },

    {"frame": "relative_time",
     "itens": {
         "after": "prep",
         "ahead": "adv",
         "antecedent": "a",
         "as": "adv",
         "behind": "adv",
         "belated": "a",
         "come on heels.": "v",
         "coming": "a",
         "early": "a",
         "erstwhile.": "a",
         "follow": "v",
         "following": "a",
         "in parallel": "a",
         "last": "a",
         "late [at night]": "a",
         "late": "a",
         "later": "adv",
         "latest": "a",
         "next": "a",
         "on time": "adv",
         "overdue": "a",
         "past": "a",
         "precede": "v",
         "preceding": "a",
         "predate": "v",
         "premature": "a",
         "previous": "a",
         "prior": "a",
         "punctual": "a",
         "punctuality": "n",
         "punctually": "adv",
         "recent": "a",
         "sooner rather than later": "adv",
         "sooner": "adv",
         "ubsequen": "a",
         "subsequently": "adv",
         "succeed": "v",
         "tardy": "a",
         "while": "c"}
     },

    {"frame": "weapon",
     "itens": {
         "AK-": "n",
         "arms": "n",
         "arsenal": "n",
         "artillery": "n",
         "assault rifle": "n",
         "atomic bomb": "n",
         "atomic weapon": "n",
         "automatic weapon": "n",
         "ballistic missile": "n",
         "biological weapon": "n",
         "biological": "a",
         "bomb": "n",
         "bow": "n",
         "BW": "n",
         "C": "n",
         "cannon": "n",
         "chemical weapon": "n",
         "chemical": "a",
         "club": "n",
         "crossbow": "n",
         "CW": "n",
         "dynamite": "n",
         "EFP": "n",
         "explosive": "a",
         "explosive": "n",
         "firearm": "n",
         "flame-thrower": "n",
         "forty-four": "n",
         "garrotte": "n",
         "gat": "n",
         "grenade": "n",
         "gun": "n",
         "handgun": "n",
         "ICBM": "n",
         "knife": "n",
         "machine-gun": "n",
         "mine": "n",
         "missile": "n",
         "mortar": "n",
         "mustard gas": "n",
         "nerve gas": "n",
         "nuclear weapon": "n",
         "nuclear": "a",
         "ordnance": "n",
         "phosgene": "n",
         "pistol": "n",
         "plastic explosive": "n",
         "revolver": "n",
         "rifle": "n",
         "rocket": "n",
         "RPG": "n",
         "Scud-B missile": "n",
         "Scud-B": "n",
         "Scud-C missile": "n",
         "shell": "n",
         "shooter": "n",
         "shotgun": "n",
         "six-shooter": "n",
         "small arms": "n",
         "spear": "n",
         "strategic nuclear weapon": "n",
         "strategic": "a",
         "sword": "n",
         "twenty-two": "n",
         "warhead": "n",
         "weapon of mass destruction": "n",
         "weapon": "n",
         "weaponry": "n",
         "WMD": "n"}
     },

    {"frame": "presence",
     "itens": {
         "absence": "n",
         "presence": "n",
         "present": "a"}
     },

    {"frame": "supply",
     "itens": {
         "afford": "v",
         "equip": "v",
         "equipment": "n",
         "fix up": "v",
         "fuel": "v",
         "furnish": "v",
         "issue": "v",
         "outfit": "v",
         "provide": "v",
         "provision": "n",
         "provision": "v",
         "supplier": "n",
         "supply": "n",
         "supply": "v"}
     },
]

itens_lexais = []
for frameelement in [a for a in frameelements]:
    for e in frameelement["itens"]:
        itens_lexais.append(str(e))

class Application:
    def __init__(self, master=None):
        self.fontePadrao = ("Arial", "10")
        self.primeiroContainer = Frame(master)
        self.primeiroContainer["pady"] = 10
        self.primeiroContainer.pack()

        self.segundoContainer = Frame(master)
        self.segundoContainer["padx"] = 20
        self.segundoContainer.pack()

        self.terceiroContainer = Frame(master)
        self.terceiroContainer["padx"] = 20
        self.terceiroContainer.pack()

        self.quartoContainer = Frame(master)
        self.quartoContainer["pady"] = 20
        self.quartoContainer.pack()

        self.quintoContainer = Frame(master)
        self.quintoContainer["pady"] = 20
        self.quintoContainer.pack()

        self.sextoContainer = Frame(master)
        self.sextoContainer["pady"] = 20
        self.sextoContainer.pack()

        self.setimoContainer = Frame(master)
        self.setimoContainer["pady"] = 20
        self.setimoContainer.pack()

        self.oitavoContainer = Frame(master)
        self.oitavoContainer["pady"] = 20
        self.oitavoContainer.pack()

        self.nonoContainer = Frame(master)
        self.nonoContainer["pady"] = 20
        self.nonoContainer.pack()

        self.decimoContainer = Frame(master)
        self.decimoContainer["pady"] = 20
        self.decimoContainer.pack()

        self.titulo = Label(self.primeiroContainer, text="Indexador de Frames - Versão 2")
        self.titulo["font"] = ("Arial", "10", "bold")
        self.titulo.pack()

        self.frameLabel = Label(self.segundoContainer, text="Qual frame é evocado pelo seguinte ítem lexical: ", font=self.fontePadrao)
        self.frameLabel.pack(side=LEFT)

        self.itemLexical = random.choice(itens_lexais)

        self.framedigitadoLabel = Label(self.terceiroContainer, text="%s: "%self.itemLexical, font=self.fontePadrao)
        self.framedigitadoLabel.pack(side=LEFT)
        self.framedigitado = Entry(self.terceiroContainer)
        self.framedigitado["width"] = 30
        self.framedigitado["font"] = self.fontePadrao
        self.framedigitado.pack(side=LEFT)

        self.verificar = Button(self.quartoContainer)
        self.verificar["text"] = "Verificar"
        self.verificar["font"] = ("Calibri", "8")
        self.verificar["width"] = 12
        self.verificar["command"] = self.verificaTipo
        self.verificar.pack()

        self.mensagem = Label(self.quartoContainer, text="", font=self.fontePadrao)
        self.mensagem.pack()

        self.sair = Button(self.quintoContainer)
        self.sair["text"] = "Sair"
        self.sair["font"] = ("Calibri", "8")
        self.sair["width"] = 12
        self.sair["command"] = self.exit
        self.sair.pack_forget()

    def verificaTipo(self):
        self.verificar.pack_forget()
        self.sair.pack()
        self.itemLexical
        frame_digitado = self.framedigitado.get()
        contador = 0
        for frameelement in [a for a in frameelements if a["frame"] == frame_digitado]:
            for e in frameelement["itens"]:
                if(e == self.itemLexical):
                    contador = contador + 1
                    self.mensagem = Label(self.quartoContainer, text="", font=self.fontePadrao, foreground='green')
                    self.mensagem.pack()
                    self.mensagem["text"] = "Correto! O ítem lexial %s evoca o frame %s" % (self.itemLexical, frame_digitado)
            if(contador == 0):
                for frameCorreto in frameelements:
                    for c in frameCorreto["itens"]:
                        if (c == self.itemLexical):
                            contador = contador + 1
                            self.mensagem = Label(self.quartoContainer, text="", font=self.fontePadrao, foreground='red')
                            self.mensagem.pack()
                            self.mensagem["text"] = "Errado! O ítem lexial %s evoca o frame %s" % (self.itemLexical, frameCorreto["frame"])

        if contador == 0:
            self.mensagem = Label(self.quartoContainer, text="", font=self.fontePadrao, foreground='red')
            self.mensagem.pack()
            self.mensagem["text"] = "Errado!"


    def exit(self):
        sys.exit()

root = Tk()
Application(root)
root.mainloop()
